### ISSUE TITLE
Git Shalector

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#105]
Fuzzy selector for git commit hash ("sha"). Present `sla` style history view, pipe through `fzf` with color, slice out selected hash with `sed`, pipe to `pbcopy`.

**Comment by gabebw** [comment]
This name is a very good name

**Comment by jkrmr** [comment]
I didn't know about `fzf --ansi` -- my world is **shattered**.

```shell
target_commit="$(git log --format=brief | fzf --ansi)"
commit_sha="${target_commit:0:7}"
echo $commit_sha | pbcopy
```

```sh
$ g show $(g sha) #FTW
```

Thanks for the idea.

What's `sla` style history view?

**Comment by gabebw** [comment]
> What's `sla` style history view?

https://github.com/christoomey/dotfiles/blob/3197f9b6d2bdbc500ccea2518b7af5638e6ab055/git/config#L45

**Comment by gabebw** [comment]
Also, you may want to slice out the hash with `awk`:

```
git --no-pager log --oneline --decorate --graph -30 | awk '{print $2}' 
a4f9c4d
963f9cf
553fa7d
be27b95
20c8c6c
abd8e88
c671f75
6086852
30261d7
40a0d83
8b2fbe8
393ca4b
84fd54a
33253e1
e21b23b
984a9a9
ca1f804
845c440
ed27e78
3a1473e
b99556f
aea50ec
af888c1
ddf943f
7e85402
01ecdd0
86ef35e
1b72860
56a68cf
580b559
```

**Comment by jkrmr** [comment]
@gabebw sweet, thanks!

**Comment by gabebw** [comment]
Hmm, `fzf --ansi` works for my custom colors. I bet git detects if it's being piped to something and strips out colors --- if I provide `--color`, git doesn't strip out the colors.

**Comment by jkrmr** [comment]
@gabebw yupyup! knowledge bombs dropping left and right tonight :bomb: :bomb: :tada:

**Comment by christoomey** [comment]
`git-shalector` (thanks for the name props @gabebw) added in aad108b56384dfb6196046dd1c9ae29fd28987ea. It looks like this:

![git-shalector](https://cloud.githubusercontent.com/assets/420113/9331112/8cbaa5e2-458b-11e5-833c-d5553cc811f0.gif)

**Comment by derekprior** [comment]
:+1: :OMG: :WANT: #hashtag.
