### ISSUE TITLE
vim plugin is missing vim-conflicted

### ISSUE THREAD

**Issue by HatBeardMe** [christoomey/dotfiles#113]
Consider merging your repo 'vim-conflicted' with the 'dotfiles' vim plugin. Or add documentation on what to download.

There is a nag message that `ConflictedVersion()` isn't found until you install the `vim-conflicted` repo.

**Comment by christoomey** [comment]
Hey @HatBeardMe, thanks for the note. I'll add this soon. As a side note, I'm guessing you're running a fork of these dotfiles locally, and that is why you hit this issue. While you're certainly welcome to do so, I frankly would recommend against it. The configurations tend to be very specific to my workflows. My other plugins are very much intended for other users, but these dotfiles will always be specific to me. That said, if they work for you, enjoy!
