### ISSUE TITLE
`tat` kills the current session

### ISSUE THREAD

**Issue by tannakartikey** [christoomey/dotfiles#126]
My [tat](https://github.com/christoomey/dotfiles/blob/master/bin/tat) script kills the current session while creating the new session. I am not sure if it's a bug or an intended behavior.

tmux version: `2.6`

## Steps to reproduce:
- Kill all the sessions and exit tmux (It's like opening the terminal after reboot)
- Change the directory e.g. `cd source/my_project`
- Press C-s C-b (as per [tmux.conf](https://github.com/christoomey/dotfiles/blob/master/tmux/tmux.conf)
- It will create the new session `my_project` but the session started by default with the home folder will be killed.

## Workaround
- Open the shell (for the first time after restarting)
- Create a split pane and then C-s C-b
- It will close down the current prompt and both the sessions will live

**Comment by christoomey** [comment]
Hi @tannakartikey, this isn't quite "intended" behavior, but is expected. For some cases I'll use the workflow you've listed in the workaround, but in most cases I use a workflow involving a custom script and additional tmux binding:

1. Hit my [key binding](https://github.com/christoomey/dotfiles/blob/51301076f2841e50018bbace6e8ed06782e05fce/tmux/tmux.conf#L60) (`<C-s><C-t>` in this case) to split open new tmux pane
2. [Display all my "active projects"](https://github.com/christoomey/dotfiles/blob/master/zsh/configs/navigation.zsh) (defined based on my `$CDPATH` setting)
3. Select from that list using [fzf](https://github.com/junegunn/fzf) fuzzy matching
4. The script then opens the selected project via `tat`

This all happens pretty quickly:
![navigation](https://user-images.githubusercontent.com/420113/42727143-18258b56-876f-11e8-9277-bd3cc08d1fae.gif)

Hopefully the above clarifies, but by all means feel free to modify the script for your own usage if you think the current behavior is less ideal for your workflows.

**Comment by tannakartikey** [comment]
Thanks!
