### ISSUE TITLE
I see you  "Remove use of reattach-to-user-namespace" 

### ISSUE THREAD

**Issue by diek** [christoomey/dotfiles#128]
I was reading your [article ](https://thoughtbot.com/blog/tmux-copy-paste-on-os-x-a-better-future)on copy and paste in tmux and thought I would check out your tmux.conf. I see you removed reattach-to-user-namespace. Are you no longer recommending the approach in the article?

**Comment by christoomey** [comment]
I still use `copy-pipe`, but since some verison of OS X in the past few years, there is no need to use `reattach-to-user-namespace`, I believe.
