### ISSUE TITLE
Vim slow to start in tmux

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#13]
Vim takes a number of seconds to open when started within tmux. This is not the case outside tmux.

**Comment by vanschelven** [comment]
Regarding the problem experienced by @vqng : I managed to solve a similar 1-second delay on startup by resetting the `SESSION_MANAGER` environment variable, i.e. adding `export SESSION_MANAGER=` in a relevant starup file. This gets rid of the 1s delay, but preserves copy-pasting using the X clipboard (at least it does so in my setup)
