### ISSUE TITLE
Update statusbar config

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#6]
[Vim airline](https://github.com/bling/vim-airline) is a lightweight option similar to powerline

Another alternative is [lightline](https://github.com/itchyny/lightline.vim)

[Vim-powerline](https://github.com/Lokaltog/vim-powerline) is intense, but requires python and is in the midst of a rewrite

**Comment by gabebw** [comment]
I use lightline: https://github.com/gabebw/dotfiles/blob/master/vim/statusline.vim

![terminal 2016-06-01 22-08-32](https://cloud.githubusercontent.com/assets/257678/15734507/63481a08-2845-11e6-9ceb-0d3324b86481.png)
