### ISSUE TITLE
Vim Startup Improvement

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#63]
Quick profile shows with vimrc => 500ms
without => 25ms (50ms for MacVim)

Time to scale back the plugins, consider implementing [lazy plugin loading via VimPlug](http://junegunn.kr/2014/07/vim-plugins-and-startup-time/)

**Comment by christoomey** [comment]
`/usr/bin/time vim -u NONE +q` => 0.01 real (so 10ms).

`/usr/bin/time vim +q` => 0.14 (so 140ms startup time with the bells and whistles). I'm fine with this.

**Comment by gabebw** [comment]
How'd you get it faster? Mine is 700ms with the bells and whistles.

**Comment by christoomey** [comment]
I recently did a hard reset of all things dotfile, and in the process I dropped a number of configurations and plugins, as well as better organizing (using `ftplugin/*` in place of `autocmd FileType *`). I'm guessing that's where the speedup comes from?
