### ISSUE TITLE
Create brewfile with utilities and cask apps

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#65]
Sample: https://gist.github.com/mwarkentin/7762077
https://github.com/gfontenot/dotfiles/blob/master/Brewfile

**Comment by Keithbsmiley** [comment]
I do this too https://github.com/Keithbsmiley/dotfiles/blob/master/osx/Brewfile but `brew-bundle` was removed from the default distribution. Here's mine https://github.com/Keithbsmiley/dotfiles/blob/master/bin/brew-bundle.rb

**Comment by gabebw** [comment]
`brew brewdle` is the official replacement: https://github.com/Homebrew/homebrew-brewdler

**Comment by Keithbsmiley** [comment]
Awesome!

**Comment by christoomey** [comment]
Brefile added in https://github.com/christoomey/dotfiles/commit/152c2bf153f18b641163277901408c1d6eefe10b.
