### ISSUE TITLE
System Copy vim plugin

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#72]
Plugin that provides `cp` map that accepts a motion to copy to system clipboard.

`cpae` => copy buffer to system clipboard

`cpiw` => inner word
`cpiW` => inner WORD

**Comment by gabebw** [comment]
Perhaps this will do what you need 😄 https://github.com/christoomey/vim-system-copy

**Comment by christoomey** [comment]
Doesn't look like anything to me. Nothing to see here... move along everyone!

Thanks @gabebw :)
