### ISSUE TITLE
Sort motion plugin

### ISSUE THREAD

**Issue by christoomey** [christoomey/dotfiles#78]
Create a plugin that sorts lines based on a motion. Map to `gs` or `<leader>so` by defualt:

`gs2j` => sort this down 2 lines
`gsap` => sort paragraph
`gsii` => sort lines at this indentation (requires [text-obj-indent](https://github.com/kana/vim-textobj-indent)) (Useful for `Gemfile` groups)

**Comment by fpereira1** [comment]
I've been using https://github.com/christoomey/vim-sort-motion - great work. I use `gsip` quite often. :)

**Comment by christoomey** [comment]
Thanks @fpereira1, glad you're enjoying it! I had forgotten about this issue here. Feeling pretty good about where sort-motion is at so I'll close this now. Hooray incremental workflow improvements!
