### ISSUE TITLE
OMG ISSUE

### ISSUE THREAD

**Issue by derekprior** [christoomey/dotfiles#96]
FIX IT.

**Comment by derekprior** [comment]
WHY ISN'T IT FIXED YET?

**Comment by derekprior** [comment]
Doesn't work for me.

**Comment by gfontenot** [comment]
hello I'm seeing this same issue in my dotfiles. have you found a fix yet?

**Comment by derekprior** [comment]
No. The author doesn't seem to support his projects.

**Comment by christoomey** [comment]
`git pull --harder` should fix.

**Comment by gabebw** [comment]
i copied these dotfiles but `git r done` still doesn't work?????? please help
