### ISSUE TITLE
Another issue

### ISSUE THREAD

**Issue by derekprior** [christoomey/dotfiles#97]
Here's another one.

**Comment by gabebw** [comment]
derek, are you drunk

**Comment by derekprior** [comment]
Chris asked me to do it.

**Comment by gfontenot** [comment]
whats up guys

**Comment by gfontenot** [comment]
stalkers of chris toomey's dotfiles unite

**Comment by christoomey** [comment]
My brother should chime in soon to round this out. Thanks for the help everyone!

**Comment by calebthompson** [comment]
This is a me too comment.

**Comment by croaky** [comment]
:thumbsup: :zap:
